### ISSUE TITLE
[Docs]: update dependabot workflow to add pre commit message and label

### ISSUE THREAD

**Issue by Anmol-Baranwal** [PiyushKalyanpy/GyanaGuru#541]
### Description

> Current One:

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      time: '01:00'
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

### Screenshots

Like this: (looks clean and according to conventions)
![image](https://github.com/rupali-codes/LinksHub/assets/74038190/5f7ae417-b0d8-44bc-89e0-0ba02621979e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue
